# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ca45fb9eaa52bfec26c10f884c7781d2d4642d03cf484ef3aa17117d8af673650b9f7872c660420efc3546cf054bb88d19320f10ebb07a55ff908fae830103b

test:
  secret_key_base: 1318cf16772856475b9d0da3a9abbc371fc19d170c2b0cd3614698fcc38243421dc8648ed2d19c3b883a1d2b3d6407ebdd5804202b1e6d28cfb852cb942b7f80

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
